services:
  docs:
    image: ghcr.io/project-gitgone/docs:latest
    restart: always
    networks:
      - internal
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.gitgone-docs.rule=Host(`${DOMAIN:-gitgone.oreades-studio.fr}`)"
      - "traefik.http.routers.gitgone-docs.entrypoints=websecure"
      - "traefik.http.routers.gitgone-docs.tls.certresolver=cloudflare"
      - "traefik.http.services.gitgone-docs.loadbalancer.server.port=3000"

networks:
  internal:
  traefik_default:
    external: true
